### ISSUE TITLE
Texture Mod Invisible

### ISSUE THREAD

**Issue by Lilothestitch16** [Telltale-Modding-Group/DDS-D3DTX-Converter#12] opened 2024-10-04 21:52 UTC
I'm working on a texture mod for Kenny but the textures turned invisible in gameplay. Is there a way I can fix this?

![20241003154928_1](https://github.com/user-attachments/assets/e6a6d435-c841-43f5-8e11-dd076b37614b)
![20241003154930_1](https://github.com/user-attachments/assets/dfd436dc-8629-4342-a33f-a083a6e45fa2)
![20241003154931_1](https://github.com/user-attachments/assets/4cdcc8f2-140e-414c-a579-3e6c922d7ba4)
![20241003154931_2](https://github.com/user-attachments/assets/dd10d2dd-e3ac-4715-9e37-b0d82623f294)

[TWDG Kenny Free Palestine.zip](https://github.com/user-attachments/files/17264056/TWDG.Kenny.Free.Palestine.zip)

**Comment by iMrShadow** [comment] 2024-10-07 20:09
You have used the wrong version of the converter again, please use the one from the fork. This is also related to #10.
I am closing the issue.

**Comment by Lilothestitch16** [comment] 2024-10-09 00:57
What fork?

**Comment by Lilothestitch16** [comment] 2024-10-09 01:48
I used the newer version 2.5.0 from the fork and the textures are still invisible. I don't know what's causing this.

**Comment by iMrShadow** [comment] 2024-10-09 14:52
After checking the d3dtx files, I have found the issue.
The textures are saved in mVersion 4, which is compatible with TWDS2 (2013), which means the Engine won't recognize these older files. I assume you converted those textures rather than those from TWD:DE.
What I would ask is - first use v2.4.0 (I will check v2.5.0 later).
Secondly, convert the **TWD:DE** d3dtx files again to generate the new JSON and replace the DDS files with your modded ones. Then convert back to D3DTX.

When you are done, contact me again and send the new textures with their respective JSON files.

**Comment by Lilothestitch16** [comment] 2024-10-09 17:21
I will do what you say and get back to you. They shouldn't be invisible.

**Comment by Lilothestitch16** [comment] 2024-10-09 22:05
[TWDG Kenny Free Palestine.zip](https://github.com/user-attachments/files/17319224/TWDG.Kenny.Free.Palestine.zip)
Here are the textures converted from 2.4.0 and 2.5.0

**Comment by iMrShadow** [comment] 2024-10-09 22:22
Right, you have extracted the textures from TWD:Season 2 (2013!!!). Which means the D3DTX version inside the JSON file is older, and it will not work with The Definitive Edition.

I specifically asked to convert the textures from the **Definitive Edition** so that the JSON file has the metadata for the newer games.
>  Secondly, convert the **TWD:DE** d3dtx files again to generate the new JSON and replace the DDS files with your modded ones. Then convert back to D3DTX.

The issue can be easily fixed - use the D3DTX files from the Definitive Edition. Afterwards, copy the newly created JSON files and replace them with the older ones. Finally, convert the DDS to D3DTX.

I repeat - the textures don't load because the D3DTX version is older, therefore incompatible.

**Comment by Lilothestitch16** [comment] 2024-10-09 23:29
Let me try that. I'm pretty sure I did convert from Definitive though.

**Comment by Lilothestitch16** [comment] 2024-10-09 23:53
Why do the Definitive Edition Textures dark in this version? 
![image](https://github.com/user-attachments/assets/82bf3951-9ea9-41ae-a81b-430008350445)

**Comment by Lilothestitch16** [comment] 2024-10-10 01:41
I finally fixed the issue.
![20241009210202_2](https://github.com/user-attachments/assets/80c743e0-19ca-4f4d-a6e1-cc676000dcc2)
![20241009210216_1](https://github.com/user-attachments/assets/6718ae18-8a55-4a27-8d5b-f2f721ea50f9)

**Comment by iMrShadow** [comment] 2024-10-10 10:15
> Why do the Definitive Edition Textures dark in this version? 

Usually images can be saved in two colour spaces - `Linear` and `sRGB`. Textures saved in `sRGB` appear darker than their `Linear` counter-part. Newer games use sRGB for most textures, while older games are Linear-only.
I am debating myself if I should change the appearance of sRGB textures on the converter, because you can differentiate in which color space you saved. However, I added a `Color Space` field in the Image Properties. It's just a matter of adding tooltips.

> I finally fixed the issue.

I am glad to hear for that. Since the issue is fixed, I am closing it.

**Closed as completed by iMrShadow** 2024-10-10 10:15 UTC
